import {
  INGREDIENT_TYPE,
  SnippetSuggestion,
  SnippetType,
  Span,
} from "./primitives";
import { spanOverlaps } from "./utils";

const RECOGNIZED_INGREDIENTS = [
  "ground chuck beef",
  "onion powder",
  "salt",
  "garlic powder",
  "ipa beer",
  "tomato sauce/puree",
  "ground ancho chili powder",
  "ground cumin",
  "paprika",
  "cocoa powder",
  "dried oregano",
  "ground cayenne pepper",
  "ground cinnamon",
  "poblano peppers",
  "kidney beans",
  "black beans",
  "grated cheddar",
  "avocado",
  "sour cream",
  "jalapeño",
  "salsa",
  "tortilla chips",
  "Fritos",
  "corn bread",
  "Abalone",
  "Açaí berries",
  "Açaí juice",
  "Acorn squash",
  "Adzuki bean paste",
  "Adzuki beans",
  "Aged Japanese kurozu",
  "Albacore tuna",
  "Alcohol",
  "Ale",
  "Alfalfa sprouts",
  "Algae",
  "Almond milk",
  "Almond paste",
  "Almonds",
  "Ancho chili powder",
  "Anchovies",
  "Anchovy paste",
  "Angus beef",
  "Apple juice",
  "Apples",
  "Apricots",
  "Apricots, Japanese",
  "Arborio rice",
  "Arctic char",
  "Artichoke, Jerusalem",
  "Artichokes",
  "Arugula",
  "Asian greens",
  "Asparagus",
  "Asparagus, Chinese",
  "Autumn crocus",
  "Avocado oil",
  "Avocados",
  "Bacon",
  "Balsamic vinegar",
  "Bananas",
  "Barbecued meat",
  "Basil",
  "Bean curd",
  "Beef",
  "Beer",
  "Beets",
  "Bell peppers",
  "Bitter almond oil",
  "Bitter cucumber",
  "Bitter melon",
  "Black beans",
  "Black cumin",
  "Black currants",
  "Black or purple rice",
  "Black pepper",
  "Black tea",
  "Blackberries",
  "Blueberries",
  "Bok choy",
  "Boysenberries",
  "Brazil nuts",
  "Bread",
  "Broccoli",
  "Broccoli sprouts",
  "Brown mustard",
  "Brown rice",
  "Brown rice syrup",
  "Brussels sprouts",
  "Buckwheat",
  "Butter",
  "Butternut squash",
  "Cabbage",
  "Canola oil",
  "Cantaloupe",
  "Carrots",
  "Cashews",
  "Cauliflower",
  "Caviar",
  "Celeriac",
  "Celery",
  "Celery seed",
  "Chamomile",
  "Cheese",
  "Cherries",
  "Chicken",
  "Chickpeas",
  "Chilli peppers",
  "Chives",
  "Chocolate",
  "Cilantro",
  "Cinnamon",
  "Clams",
  "Coconut",
  "Coconut oil",
  "Coffee",
  "Collard greens",
  "Corn",
  "Corn oil",
  "Crab",
  "Cranberries",
  "Cream",
  "Cucumbers",
  "Cumin",
  "Curcumin",
  "Currants",
  "Daidzein",
  "Dal",
  "Dill",
  "Dried herring",
  "Dried mackerel",
  "Dry beans",
  "Edamame",
  "Eggs",
  "Escargot",
  "Fennel",
  "Fennel seed",
  "Fermented bean paste",
  "Fermented milk",
  "Flaxseed",
  "Flaxseed oil",
  "Fried potatoes",
  "Garbanzo beans",
  "Garden cress",
  "Garlic",
  "Genistein",
  "Ghee",
  "Ginger",
  "Grape seed oil",
  "Grapefruit",
  "Grapes",
  "Gravy",
  "Green beans",
  "Green onions",
  "Green papaya",
  "Green peas",
  "Green tea",
  "Greens",
  "Guacamole",
  "Halibut",
  "Ham",
  "Herring",
  "Holy basil",
  "Honey",
  "Honeydew melon",
  "Horseradish",
  "Hot peppers",
  "Hummus",
  "Indian mustard",
  "Kale",
  "Kefir",
  "Kelp",
  "Kidney beans",
  "King mackerel",
  "Kiwifruit",
  "Kohlrabi",
  "Kumquats",
  "Lake trout",
  "Lamb",
  "Lard",
  "Lavender",
  "Leeks",
  "Lemons",
  "Lentils",
  "Lettuce",
  "Lima beans",
  "Limes",
  "Lingonberries",
  "Liquor",
  "Liver",
  "Lobster",
  "Loganberries",
  "Long pepper",
  "Low-fat yogurt",
  "Macadamia nut oil",
  "Macadamia nuts",
  "Mackerel",
  "Maitake mushrooms",
  "Mangoes",
  "Mangosteen",
  "Margarine",
  "Marionberrries",
  "Maté",
  "Mayonnaise",
  "Melons",
  "Mexican oregano",
  "Milk",
  "Mint",
  "Mint tea",
  "Mung beans",
  "Mushrooms",
  "Muskmelon",
  "Mussels",
  "Mustard",
  "Mustard greens",
  "Mustard oil",
  "Mutton",
  "Navy beans",
  "Oatmeal",
  "Oats",
  "Octopus",
  "Ohyo",
  "Olive oil",
  "Olives",
  "Onions",
  "Oranges",
  "Oregano",
  "Oysters",
  "Papaya",
  "Papaya seeds",
  "Paprika",
  "Parsley",
  "Parsnips",
  "Partially-hydrogen. oil",
  "Passion fruit",
  "Pâtés",
  "Paw paw",
  "Peaches",
  "Peanut oil",
  "Peanuts",
  "Pears",
  "Peas",
  "Pecans",
  "Peppermint",
  "Persipan",
  "Pesto sauce",
  "Pickled papaya",
  "Pickled watermel. rind",
  "Pickles",
  "Pineapple",
  "Pinto beans",
  "Pistachio nuts",
  "Plantago",
  "Plantains",
  "Plums",
  "Pomegranate juice",
  "Pomegranates",
  "Pork",
  "Portobello mushrooms",
  "Potatoes",
  "Prunes",
  "Pumpkin seeds",
  "Pumpkins",
  "Radicchio",
  "Radish",
  "Raisins",
  "Rapeseed oil",
  "Rapini",
  "Raspberries",
  "Red bean paste",
  "Red beans",
  "Red cabbage",
  "Red currants",
  "Red onions",
  "Red pepper flakes",
  "Red pepper paste",
  "Red rice",
  "Red spinach",
  "Red wine vinegar",
  "Reishi mushrooms",
  "Rhubarb",
  "Ribs",
  "Rice",
  "Rice bran",
  "Rice bran oil",
  "Rice wine vinegar",
  "Risotto",
  "Roast beef",
  "Roasted almonds",
  "Roasted pork",
  "Roe",
  "Rolled oats",
  "Romaine lettuce",
  "Rosemary",
  "Rutabagas",
  "Rye",
  "Safflower oil",
  "Saffron",
  "Sage",
  "Sage tea",
  "Salmon, wild",
  "Salt",
  "Sardines",
  "Sauerkraut",
  "Sausages",
  "Scallions",
  "Scallops",
  "Seaweed",
  "Sesame oil",
  "Sesame seeds",
  "Shallots",
  "Shellfish",
  "Shiitake mushrooms",
  "Shrimp",
  "Smoked mackerel",
  "Snails",
  "Snow peas",
  "Soba noodles",
  "Soy infant formula",
  "Soy milk",
  "Soy protein bars",
  "Soy protein isolate",
  "Soybean curd",
  "Soybean oil",
  "Soybeans",
  "Spaghetti squash",
  "Spearmint",
  "Spinach",
  "Split peas",
  "Squash",
  "Steak",
  "Strawberries",
  "String beans",
  "Subtropical ginger",
  "Sugar",
  "Sugar beets",
  "Sugar snap peas",
  "Summer squash",
  "Sunflower oil",
  "Sunflower seeds",
  "Sweet peas",
  "Sweet potatoes",
  "Tabasco sauce",
  "Tahini",
  "Tallow",
  "Tangerines",
  "Tartary buckwheat",
  "Tea",
  "Thyme",
  "Tofu",
  "Tomato paste",
  "Tomatoes",
  "Tropical ginger",
  "Turkey",
  "Turkey bacon",
  "Turmeric",
  "Turnip greens",
  "Turnips",
  "Veal",
  "Vinegar",
  "Wakame",
  "Walnut oil",
  "Walnuts",
  "Wasabi",
  "Watercress",
  "Watermelon",
  "Watermelon seeds",
  "Well-done meat",
  "Wheat bran",
  "Wheat germ",
  "Wheat grass",
  "White beans",
  "White bread",
  "White button mush.",
  "White pepper",
  "White tea",
  "White vinegar",
  "Whole wheat bread",
  "Wild ginger",
  "Wild rice",
  "Wine",
  "Winter squash",
  "Yams",
  "Yerba maté",
  "Yogurt",
  "Zucchini",
];

const RECOGNIZED_AISLES: { [key: string]: string } = {
  "ground chuck beef": "🥬 Produce",
  "onion powder": "🥬 Produce",
  salt: "🍞 Baking",
  "garlic powder": "🧂 Spices",
  "ipa beer": "🍺 Alcohol",
  "tomato sauce/puree": "🥫 Canned Goods",
  "ground ancho chili powder": "🧂 Spices",
  "ground cumin": "🧂 Spices",
  paprika: "🧂 Spices",
  "cocoa powder": "🍞 Baking",
  "dried oregano": "🧂 Spices",
  "ground cayenne pepper": "🧂 Spices",
  "ground cinnamon": "🧂 Spices",
  "poblano peppers": "🥬 Produce",
  "kidney beans": "🥫 Canned Goods",
  "black beans": "🥫 Canned Goods",
  "grated cheddar": "🐮 Dairy",
  avocado: "🥬 Produce",
  "sour cream": "🐮 Dairy",
  jalapeño: "🥬 Produce",
  salsa: "Condiments",
  "tortilla chips": "🍿 Snacks",
  Fritos: "🍿 Snacks",
  "corn bread": "🥪 Bakery",
};

export const ingredientSnippetType: SnippetType = {
  name: "Ingredient",
  icon: "🥕",
  color: "#ffc107",
  suggest: (text: string): SnippetSuggestion[] => {
    let matches: Span[] = [];
    // We could probably do this faster if we combined all the known strings into one regex,
    // but this is simpler to reason about and seems fast enough for now.
    for (const stringTemplate of RECOGNIZED_INGREDIENTS) {
      for (const match of text.matchAll(new RegExp(stringTemplate, "ig"))) {
        const from = match.index ?? 0;
        const to = from + match[0].length;
        // Only add the match if it doesn't overlap with other existing matches.
        // This prevents weird overlapping matches
        if (!matches.some((existing) => spanOverlaps(existing, [from, to]))) {
          matches.push([from, to]);
        }
      }
    }

    return matches.map(([from, to]) => ({
      span: [from, to],
      snippetTypeId: INGREDIENT_TYPE,
    }));
  },

  // TODO: this will parse out structured data for the ingredient
  parse: (text: string) => {
    return {
      aisle: RECOGNIZED_AISLES[text] ?? "Unknown",
    };
  },

  properties: [{ id: "aisle", name: "Aisle", type: "string" }],
};
